config/routes.rb
Rails.application.routes.draw do
  get 'purchase/index'
  get 'purchase/done'
  get 'credit_cards/index'
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    
  }
  root  "tops#index"
  resources :tops, only: [:index,:show,:new]  
  resources :user_adresses, only: [:index,:new,:create]
  resources :credit_cards, only: [:index, :new, :show,:delete] do
    collection do
      post 'show', to: 'credit_cards#show'
      post 'pay', to: 'credit_cards#pay'
      post 'delete', to: 'credit_cards#delete'
    end
  end

  resources :products, only: [:index, :edit, :update, :new, :create, :show, :destroy] do

    collection do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
    end
  resources :purchase, only: [:index] do
    collection do
      get 'index', to: 'purchase#index'
      post 'pay', to: 'purchase#pay'
      get 'done', to: 'purchase#done'
    end
  end
end

  namespace :api do
      resources "sell", controller: :products, only: :child, defaults: { format: 'json' } do
        collection do
          get 'child'
        end
      end
      resources "sell", controller: :products, only: :grand_child, defaults: { format: 'json' } do
        collection do
          get 'grand_child'
        end
      end
      resources "destroy", controller: :products, only: :image_destroy, defaults: { format: 'json' } do
        collection do
          delete "image_destroy"
        end
      end
    end


  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
end

app/views/shared/_card_input.html.haml
.card__main
  = form_tag( pay_credit_cards_path,method: :post, id: 'charge-form', name: 'inputForm', class: 'main__container') do
    .main__container__header
      クレジットカード情報入力
    .main__container__form
      .main__container__form__card
        .main__container__form__card__title
          カード番号
        .main__container__form__card__require
          必須
        = text_field_tag "number", "", maxlength: "16",type: "text", placeholder:"半角数字のみ", class: "number", id: "card_number"
        .main__container__form__card__image
      .main__container__form__limit
        .main__container__form__limit__title
          有効期限
        .main__container__form__limit__require
          必須
        .main__container__form__limit__form
          .main__container__form__limit__month
            %select#exp_month{name: "exp_month", type: "text"}
              %option{value: ""} --
              %option{value: "1"}01
              %option{value: "2"}02
              %option{value: "3"}03
              %option{value: "4"}04
              %option{value: "5"}05
              %option{value: "6"}06
              %option{value: "7"}07
              %option{value: "8"}08
              %option{value: "9"}09
              %option{value: "10"}10
              %option{value: "11"}11
              %option{value: "12"}12
            %span 月
          .main__container__form__limit__year
            %select#exp_year{name: "exp_year", type: "text"}
              %option{value: ""} --
              %option{value: "2019"}19
              %option{value: "2020"}20
              %option{value: "2021"}21
              %option{value: "2022"}22
              %option{value: "2023"}23
              %option{value: "2024"}24
              %option{value: "2025"}25
              %option{value: "2026"}26
              %option{value: "2027"}27
              %option{value: "2028"}28
              %option{value: "2029"}29
            %span 年
      .main__container__form__security
        .main__container__form__security__title
          セキュリティーコード
        .main__container__form__security__require
          必須
        = text_field_tag "cvc", "", maxlength: "4",type: "text", id: "cvc", placeholder:"カードの背面4桁もしくは3桁の番号", class: "cvc"
        #card_token
      .main__container__form__question
        .main__container__form__question__mark
          %span ?
          カードの裏面の番号とは？
      .main__container__form__btn
        = submit_tag "追加する" , id:"token_submit", class: "main__container__form__btn__red" 

app/views/shared/_credit_card.html.haml
.credit-card
  .credit-card_content
    %label 登録クレジットカード情報
    .credit-card_number
      %br
      = "**** **** **** " + @default_card_information.last4
      %br
    .credit-card_px
      - exp_month = @default_card_information.exp_month.to_s
      - exp_year = @default_card_information.exp_year.to_s.slice(2,3)
      = exp_month + " / " + exp_year
    .credit-card_submit-btn
      = form_tag(delete_credit_cards_path, method: :post, id: 'charge-form',  name: "inputForm") do
        %input{ type: "hidden", name: "card_id", value: "" }
        %button 削除する

app/views/shared/_credit_page.html.haml
.credit-method
  .user-card__content
    %h2 支払い方法
    .user-card__content__inner
      .user-card__content__inner--text
        %h3 クレジットカード一覧
      .user-card__content__inner--btn
        = link_to new_credit_card_path,class: "user-card__content__inner--btn--add" do
          %i.fas.fa-credit-card
          クレジットカードを追加する
      .user-card__content__inner--help
        = link_to "#" do
          支払い方法について
          %i.fas.fa-chevron-right

app/views/shared/_loginfooter.html.haml
.single-fotter
  %ul.clearfix
    %li.footer-list
      =link_to "#",class:"a" do
        プライバシーポリシー
    %li.footer-list
      =link_to "#",class:"a" do
        フリマ利用規約
    %li.footer-list
      =link_to "#", class: "a" do
        特定商取引に関する表記
  .fotter-pict
    = image_tag 'furima.svg', height: '60', width: '80'

app/views/shared/_loginheader.html.haml
.single-header-user
  .single-header-user-icon-list
    .single-header__icon-user
      = link_to root_path do
        = image_tag 'furima.svg', height: '80', width: '185'

app/views/shared/_logout.html.haml
.logout-method
  .logout-inner
    .logout-content
      .logout-content__single
        .logout__content__single--btn
          = link_to destroy_user_session_path,method: :delete do
            ログアウト

app/views/shared/_mypage_top.html.haml
.mypage-method
  %section.mypage-content__user-icon
    = link_to '#' do
      %figure
        = image_tag 'user-icon.jpg', size: '60x60'
      %h2.mypage-content__user-name.bold
        = @nickname
      .mypage-content__status
        .mypage-content__reviews
          評価&nbsp
          %span.mypage-content__reviews.bold<>
            5
        .mypage-content__sell
          出品数
          %span.mypage-content__sell.bold<>
            15
  %section.mypage-content__main-tab-container
    %ul.mypage-content__tabs
      %li.mypage-content__tab.mypage-content__tab--active
        %h3
          = link_to '#', id: 'mypage-content__tab-notification' do
            お知らせ
      %li.mypage-content__tab
        %h3
          = link_to '#', id: 'mypage-content__tab-todo' do
            やることリスト
    .mypage-content__tab-content
      %ul.mypage-content__item-list.mypage-content__item-list--active{ id: 'mypage-content__item-list-notification' }
        %li
          = link_to '#', class: 'mypage-content__item-link' do
            %figure
              = image_tag 'profile.jpg', size: '48x48'
            .mypage-content__item-body
              .mypage-content__item-text
                新型コロナウイルス感染拡大に伴う衛生マスクの出品禁止について
              %time
                = icon 'far', 'clock'
                %span
                  2 時間前
            = icon 'fas', 'chevron-right'
        %li
          = link_to '#', class: 'mypage-content__item-link' do
            %figure
              = image_tag 'profile.jpg', size: '48x48'
            .mypage-content__item-body
              .mypage-content__item-text
                【最大1000円分ポイントプレゼント！】詳しくはこちら♪
              %time
                = icon 'far', 'clock'
                %span
                  7 時間前
            = icon 'fas', 'chevron-right'
        %li
          = link_to '#', class: 'mypage-content__item-link' do
            %figure
              = image_tag 'profile.jpg', size: '48x48'
            .mypage-content__item-body
              .mypage-content__item-text
                要冷蔵食品に関するお知らせ
              %time
                = icon 'far', 'clock'
                %span
                  2 日前
            = icon 'fas', 'chevron-right'
        %li
          = link_to '#', class: 'mypage-content__item-link' do
            %figure
              = image_tag 'profile.jpg', size: '48x48'
            .mypage-content__item-body
              .mypage-content__item-text
                マスクなど感染予防品の取引に関するご協力のお願い
              %time
                = icon 'far', 'clock'
                %span
                  3 日前
            = icon 'fas', 'chevron-right'
        %li
          = link_to '#', class: 'mypage-content__item-link' do
            %figure
              = image_tag 'profile.jpg', size: '48x48'
            .mypage-content__item-body
              .mypage-content__item-text
                【重要】あんしんスマホサポート機能の終了のお知らせ
              %time
                = icon 'far', 'clock'
                %span
                  5 日前
            = icon 'fas', 'chevron-right'
        %li.mypage-content__go-list
          = link_to '#' do
            一覧を見る
      %ul.mypage-content__item-list{ id: 'mypage-content__item-list-todo' }
        %li.mypage-content__item-not-found
          現在、やることリストはありません
  %section.mypage-content__secondary-tab-container
    %h2.mypage-content__tab-head
      購入した商品
    %ul.mypage-content__tabs
      %li.mypage-content__tab.mypage-content__tab--active
        %h3
          = link_to '#', id: 'mypage-content__tab-transaction-now' do
            取引中
      %li.mypage-content__tab
        %h3
          = link_to '#', id: 'mypage-content__tab-transaction-old' do
            過去の取引
    .mypage-content__tab-content
      %ul.mypage-content__item-list.mypage-content__item-list--active{ id: 'mypage-content__item-list-transaction-now' }
        %li.mypage-content__item-not-found
          取引中の商品がありません
      

app/views/shared/_topfooter.html.haml
.app
  .app__main
    .app__main--top
      誰でもかんたん、人生を変えるフリマアプリ
    .app__main--midle
      今すぐダウンロード！
    .app__main--bottom
      =link_to url="#" ,class:"cbtn"do
        = image_tag 'app.svg',  height: '120', width: '150', class: 'iamge3'
      =link_to url="#" ,class:"dbtn" do
        = image_tag 'google.svg',  height: '120', width: '150', class: 'iamge3'
.footer
  %ul.contents
    %li.content
      .content__head
        FURIMAについて
      %ul
        %li
          =link_to url="#" ,class:"ebtn"do
            会社概要（運営会社）
        %li
          =link_to url="#" ,class:"ebtn"do
            プライバシーポリシー
        %li
          =link_to url="#" ,class:"ebtn"do
            FURIMA利用規約
        %li
          =link_to url="#" ,class:"ebtn"do
            ポイントに関する特約
    %li.content
      .content__head
        FURIMAを見る
      %ul
        %li
          =link_to url="#" ,class:"fbtn"do
            カテゴリーー覧
        %li
          =link_to url="#" ,class:"gbtn"do
            ブランドーー覧
    %li.content
      .content__head
        ヘルプ＆ガイド
      %ul
        %li
          =link_to url="#" ,class:"hbtn"do
            FURIMAガイド
        %li
          =link_to url="#" ,class:"ibtn"do
            FURIMAロゴ利用ガイドライン
        %li
          =link_to url="#" ,class:"jbtn"do
            お知らせ
  .footer__logo
    =link_to url="products" ,class:"jbtn"do
      = image_tag 'furima2.svg',  height: '120', width: '150', class: 'iamge11'
    %p
      ©️FURIMA
-if user_signed_in?
  =link_to "products",class:"sell" do
    %span.selld
      出品する
    = image_tag 'icon_camera.png',  height: '70px', width: '70px', class: 'iamge11'
-else
  =link_to new_user_session_path,class:"sell" do
    %span.selld
      出品する
    = image_tag 'icon_camera.png',  height: '70px', width: '70px', class: 'iamge11'

app/views/shared/_topheader.html.haml
.header
  .header__main
    .header__main--top
      .header__main--top-icon
        = link_to root_path do
          = image_tag 'furima.svg', height: '100', width: '120', class: 'image1'
      .header__main--top-searchbox
        %form
          %input{type:"text",class:"left"}
          %input{type:"submit",value:"",class:"right"}
            = link_to url="#" do
              = image_tag 'megane.svg',height: '20px', width: '20px', class: 'image2'
    .header__main--bottom
      .header__main--bottom-left
        %ul.left__items
          %li.left__item
            = link_to url="#"  do
              カテゴリー
            %ul.left__item--left
              - @parents.each do |parent|
                %li.left__item--left__items
                  = link_to "#{parent.name}", url="#",class: "parent_category",id: "#{parent.id}"
            %ul.left__item--left__children
            %ul.left__item--left__grand__children

        .right-item
          = link_to url="#" do
            ブランド
      .header__main--bottom-right
      -if user_signed_in? 
        .left-name
          = link_to destroy_user_session_path,method: :delete do
            ログアウト
        .right-name
          = link_to user_adresses_path do
            マイページ
      -else
        .left-name
          = link_to new_user_session_path do
            ログイン
        .right-name
          = link_to new_user_registration_path do
            新規会員登録