config/routes.rb
Rails.application.routes.draw do
  get 'purchase/index'
  get 'purchase/done'
  get 'credit_cards/index'
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    
  }
  root  "tops#index"
  resources :tops, only: [:index,:show,:new]  
  resources :user_adresses, only: [:index,:new,:create]
  resources :credit_cards, only: [:index, :new, :show,:delete] do
    collection do
      post 'show', to: 'credit_cards#show'
      post 'pay', to: 'credit_cards#pay'
      post 'delete', to: 'credit_cards#delete'
    end
  end

  resources :products, only: [:index, :edit, :update, :new, :create, :show, :destroy] do

    collection do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
    end
  resources :purchase, only: [:index] do
    collection do
      get 'index', to: 'purchase#index'
      post 'pay', to: 'purchase#pay'
      get 'done', to: 'purchase#done'
    end
  end
end

  namespace :api do
      resources "sell", controller: :products, only: :child, defaults: { format: 'json' } do
        collection do
          get 'child'
        end
      end
      resources "sell", controller: :products, only: :grand_child, defaults: { format: 'json' } do
        collection do
          get 'grand_child'
        end
      end
      resources "destroy", controller: :products, only: :image_destroy, defaults: { format: 'json' } do
        collection do
          delete "image_destroy"
        end
      end
    end


  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :images, dependent: :destroy

  belongs_to :category
  accepts_nested_attributes_for :images, allow_destroy: true
  belongs_to :category
  validates :images, presence: true
  validates :name, presence: true
  validates :description, presence: true
  validates :category_id, presence: true
  validates :condition_id, presence: true
  validates :postage_burden, presence: true
  validates :sending_method_id, presence: true
  validates :area_id, presence: true
  validates :scheduled_sending_date, presence: true
  validates :price, presence: true
end

app/controllers/api/products_controller.rb
class Api::ProductsController < ApplicationController

  def child
    @child_categories = Category.where('ancestry = ?', "#{params[:id]}")
    respond_to do |format|
      format.html
      format.json
    end
  end

  def grand_child
    unless params[:id].empty?
      id = "/" + "#{params[:id]}"
      @grand_child_categories = Category.where('ancestry LIKE(?)', "%#{id}")
      respond_to do |format|
        format.html
        format.json
      end
    end
  end

  def image_destroy
    image = Image.find(params[:img_id])
    if image.product.seller_id == current_user.id
      image.destroy
    end
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_item, only: [:edit, :destroy, :show]

  def index
    @products = Product.includes(:images).order('created_at DESC')
    @product = Product.new
    4.times { @product.images.build }
    @product.images.new
    @category_parent_array = ["---"]
    Category.where(ancestry: nil).each do |parent|
    @category_parent_array << parent.name
    end
  end

  def show
    # @address = UserAdress.find(current_user.id)
    @parents = Category.where(ancestry: nil)
    
    @condition = Condition.find(@product.condition_id)
    @area = Area.find(@product.area_id)
    @sending_method = SendingMethod.find(@product.sending_method_id)
    @category = Category.find(@product.category_id)
    @user = User.find(@product.seller_id)
    if @product.brand_id.present?
       @brand = Brand.find(@product.brand_id)
    else
    end
  end

  def new
  end

  def get_category_children
    @category_children = Category.find_by(name: params[:parent_name]).children
  end

  def get_category_grandchildren
    @category_grandchildren = Category.find("#{params[:child_id]}").children
  end

  def create
    @category_parent_array = ["---"]
    Category.where(ancestry: nil).each do |parent|
    @category_parent_array << parent.name
    end
    @product = Product.new(product_params)
    if @product.save
      redirect_to root_path
    else
      4.times { @product.images.build }
      render :index
    end
  end

  def edit
    @product = Product.find(params[:id])
    image_amount = 5
    image_amount.freeze
    num = image_amount - (@product.images.length)
    num.times { @product.images.build }

    grandchild_category = @product.category
    child_category = grandchild_category.parent
    @category_parent_array = Category.where(ancestry: nil).pluck(:name)
    @category_children_array = Category.where(ancestry: child_category.ancestry)
    @category_grandchildren_array = Category.where(ancestry: grandchild_category.ancestry)

  end

  def new
  end

  def update
    @product = Product.find(params[:id])
    if @product.update(update_params) && params.require(:product).keys[0] == "images_attributes"
      redirect_to root_path ,notice: '商品を編集しました'
    else
      image_amount = 5
      image_amount.freeze
      num = image_amount - (@product.images.length)
      num.times { @product.images.build }
  
      grandchild_category = @product.category
      child_category = grandchild_category.parent
      @category_parent_array = Category.where(ancestry: nil).pluck(:name)
      @category_children_array = Category.where(ancestry: child_category.ancestry)
      @category_grandchildren_array = Category.where(ancestry: grandchild_category.ancestry)
      render :edit
    end
  end

  def destroy
    if @product.destroy
      redirect_to root_path
    else
      render product_path(product.product.id)
    end
  end
  private


  def product_params
    @img_attr = params[:product][:images_attributes]
    params.require(:product).permit(:name, :category_id, :brand_id, :price, :description, :condition_id, :postage_burden, :sending_method_id, :area_id, :scheduled_sending_date, :size, images_attributes: [:image_url,:_destroy, :id]).merge(seller_id: current_user.id)
  end


  def update_params
    params.require(:product).permit(:name, :category_id, :brand_id, :price, :description, :condition_id, :postage_burden, :sending_method_id, :area_id, :scheduled_sending_date, :size, images_attributes: [:image_url,:_destroy,:id]).merge(seller_id: current_user.id,)if @image.nil?
  end
  def set_item
    @product = Product.find(params[:id])
  end

end

app/views/products/edit.html.haml
.single-header-user
  .single-header-user-icon-list
    .single-header__icon-user
      = image_tag 'http://furima.tokyo/assets/logo-d3d78326971d78b06e3d6f0ba666d025a8ad681286b4d9e00e7dbe8673bcfd23.svg', height: '80', width: '185'

.sell
  - if @product.errors.any? 
    - @product.errors.full_messages.each do |message| 
      %p
        = message
  = form_for(@product, { multipart: true }) do |f|
    .sell__title 商品の情報を編集
    .sell__image
      = f.label :image, "出品画像"
      %span.required
      %p.max 最大10枚までアップロードできます
      .sell__image-select
        ドラッグアンドドロップ
        %br
        またはクリックしてファイルをアップロード
        %ul.sell__image-select__ul
          - @product.images.each_with_index do |image, i|
            %label{class: "sell__image-select__ul-text ul-id-#{i}"}
              = f.fields_for :images, image do |img|
                = img.file_field :image_url, "data-id": "#{i}"
                %li
                  -if image.id.present?
                    = image_tag "#{img.object.image_url}",size: "114x116",class:"product_image"
                .btn-box
                  %a 編集
                  %a{ class: "delete-btn", "data-imgid": "#{image.id}" }削除
          

       
    .sell__about
      .sell__about__name
        = f.label :name, "商品名"
        %span.required
        = f.text_field :name, class: "form", placeholder: "商品名（必須40文字まで）"
      .sell__about__description
        = f.label :description, "商品の説明"
        %span.required
        = f.text_area :description, class: "sell__about-description__form", placeholder: "商品の説明（必須 1,000文字以内）（色、素材、重さ、定価、注意点など）例）2010年頃に1万円で購入したジャケットです。ライトグレーで傷はありません。あわせやすいのでおすすめです。"
    .sell__about.clearfix
      .sell__about__left 商品の詳細
      .sell__about__righ
        .sell__about__right__wraps
          = f.label :category_id, "カテゴリー"
          %span.required
          .sell__about__right__wrap-box.parent
            = f.select :category_id, @category_parent_array, {selected:@product.category.parent.parent.name}, {class: 'listing-select-wrapper__box--select', id: 'parent_category'}
          .sell__about__right__wrap-box.select#children_wrapper
            = f.select :category_id, options_for_select(@category_children_array.map{|b| [b.name, b.id, {data:{category: b.id}}]}, {prompt: "指定なし", selected: @product.category.parent.id}), {}, {class: 'listing-select-wrapper__box--select', id: 'child_category'}
          .sell__about__right__wrap-box.select#grandchildren_wrapper
            = f.select :category_id, options_for_select(@category_grandchildren_array.map{|b| [b.name, b.id, {data:{category: b.id}}]}, {prompt: "指定なし", selected: @product.category.id}), {}, {class: 'listing-select-wrapper__box--select', id: 'grandchild_category'}
        .sell__about__right__wrap
          = f.label :size_id, "サイズ"
          %span.required-gray
          .sell__about__right__wrap-box.parent
            = f.text_field :size, class: "form", placeholder: "サイズを入力して下さい"
        .sell__about__right__wrap
          = f.label :brand_id, "ブランド"
          %span.required-gray
          .sell__about__right__wrap-box
            = f.collection_select(:brand_id, Brand.all, :id, :name, prompt: "---", class: "form")
        .sell__about__right__wrap
          = f.label :condition_id, "商品の状態"
          %span.required
          .sell__about__right__wrap-box
            = f.collection_select(:condition_id, Condition.all, :id, :name, prompt: "---")
            %i.fas.fa-chevron-down

    .sell__about.clearfix
      .sell__about__left 配送について
      .sell__about__right
        .sell__about__right__wrap
          = f.label :postage_burden, "配送料の負担"
          %span.required
          .sell__about__right__wrap-box
            = f.select :postage_burden, [["送料込み(出品者負担)",0],["着払い(購入者負担)",1]], prompt: "選択してください", class: "select"
            %i.fas.fa-chevron-down
        .sell__about__right__wrap
          = f.label :sending_method_id, "配送の方法"
          %span.required
          .sell__about__right__wrap-box
            = f.collection_select(:sending_method_id, SendingMethod.all, :id, :name, prompt: "---")
            %i.fas.fa-chevron-down
        .sell__about__right__wrap
          = f.label :area_id, "発送元の地域"
          %span.required
          .sell__about__right__wrap-box
            = f.collection_select(:area_id, Area.all, :id, :name, prompt: "---")
            %i.fas.fa-chevron-down

        .sell__about__right__wrap
          = f.label :scheduled_sending_date, "発送までの日数"
          %span.required
          .sell__about__right__wrap-box
            = f.select :scheduled_sending_date,[["1~2日で発送", 0], ["2~3日で発送", 1], ["4~7日で発送", 2]], prompt: "---", class: "select"
            %i.fas.fa-chevron-down

    .sell__about.clearfix
      .sell__about__left 販売価格(300〜9,999,999)
      .sell__about__right
        .sell__about__right__wrap
          .sell__about__right__wrap__price
            .sell__about__right__wrap__price-label
              = f.label :price, "価格"
              %span.required
            .sell__about__right__wrap__price-input
              ¥
              .sell__about__right__wrap__price-input-form
                = f.number_field :price, placeholder: "例）300", class: "form"

        .sell__about__right__wrap__fee.clearfix
          .sell__about__right__wrap__fee-left
            販売手数料 (10%)
          .sell__about__right__wrap__fee-right
            ¥
        .sell__about__right__wrap__profit
          .sell__about__right__wrap__profit-left
            販売利益
          .sell__about__right__wrap__profit-right
            ¥
    .sell__about.clearfix
      .sell__about__bottom
          
        = f.submit "編集する", class: 'sell__about__bottom-btn submit'
        %button{type: "button", onclick: "history.back()", class: 'sell__about__bottom-btn back'} もどる


      .sell__about__bottom-text
        %p
          = link_to '#' do
            禁止されている出品
          、
          = link_to '#' do
            行為
          を必ずご確認ください。
        %p
          またブランド品でシリアルナンバー等がある場合はご記載ください。
          = link_to '#' do
            偽ブランド
          の販売は犯罪であり処罰される可能性があります。
        %p
          また、出品をもちまして
          = link_to '#' do
            加盟店規約
          に同意したことになります。


.single-fotter
  %ul.clearfix
    %li.footer-list
      =link_to "#",class:"a" do
        プライバシーポリシー
    %li.footer-list
      =link_to "#" ,class:"a" do
        フリマ利用規約
    %li.footer-list
      =link_to "#", class: "a" do
        特定商取引に関する表記
  .fotter-pict
    = image_tag 'http://furima.tokyo/assets/logo-d3d78326971d78b06e3d6f0ba666d025a8ad681286b4d9e00e7dbe8673bcfd23.svg', height: '60', width: '80'
  .footer-logo
    © FURIMA

app/views/products/index.html.haml
.single-header-user
  .single-header-user-icon-list
    .single-header__icon-user
      = link_to root_path do
        = image_tag 'http://furima.tokyo/assets/logo-d3d78326971d78b06e3d6f0ba666d025a8ad681286b4d9e00e7dbe8673bcfd23.svg', height: '80', width: '185'

.sell
  - if @product.errors.any? 
    - @product.errors.full_messages.each do |message| 
      %p.messages
        = message
  = form_for(@product) do |f|
    .sell__title 商品の情報を入力
    .sell__image
      = f.label :image, "出品画像"
      %span.required
      %p.max 最大10枚までアップロードできます
      .sell__image-select
        ドラッグアンドドロップ
        %br
        またはクリックしてファイルをアップロード
        %ul.sell__image-select__ul
          - @product.images.each_with_index do |image, i|
            %label{class: "sell__image-select__ul-text ul-id-#{i}"}
              = f.fields_for :images, image do |img|
                = img.file_field :image_url, "data-id": "#{i}"
                %li
                .btn-box
                  %a 編集
                  %a.delete-btn 削除
          

       
    .sell__about
      .sell__about__name
        = f.label :name, "商品名"
        %span.required
        = f.text_field :name, class: "form", placeholder: "商品名（必須40文字まで）"
      .sell__about__description
        = f.label :description, "商品の説明"
        %span.required
        = f.text_area :description, class: "sell__about-description__form", placeholder: "商品の説明（必須 1,000文字以内）（色、素材、重さ、定価、注意点など）例）2010年頃に1万円で購入したジャケットです。ライトグレーで傷はありません。あわせやすいのでおすすめです。"
    .sell__about.clearfix
      .sell__about__left 商品の詳細
      .sell__about__righ
        .sell__about__right__wraps
          = f.label :category_id, "カテゴリー"
          %span.required
          .sell__about__right__wrap-box.parent
            = f.select :category_id, @category_parent_array, {}, {class: 'listing-select-wrapper__box--select', id: 'parent_category'}
        .sell__about__right__wrap
          = f.label :size_id, "サイズ"
          %span.required-gray
          .sell__about__right__wrap-box.parent
            = f.text_field :size, class: "form", placeholder: "サイズを入力して下さい"
        .sell__about__right__wrap
          = f.label :brand_id, "ブランド"
          %span.required-gray
          .sell__about__right__wrap-box
            = f.collection_select(:brand_id, Brand.all, :id, :name, prompt: "---", class: "form")
        .sell__about__right__wrap
          = f.label :condition_id, "商品の状態"
          %span.required
          .sell__about__right__wrap-box
            = f.collection_select(:condition_id, Condition.all, :id, :name, prompt: "---")
            %i.fas.fa-chevron-down

    .sell__about.clearfix
      .sell__about__left 配送について
      .sell__about__right
        .sell__about__right__wrap
          = f.label :postage_burden, "配送料の負担"
          %span.required
          .sell__about__right__wrap-box
            = f.select :postage_burden, [["送料込み(出品者負担)",0],["着払い(購入者負担)",1]], prompt: "選択してください", class: "select"
            %i.fas.fa-chevron-down
        .sell__about__right__wrap
          = f.label :sending_method_id, "配送の方法"
          %span.required
          .sell__about__right__wrap-box
            = f.collection_select(:sending_method_id, SendingMethod.all, :id, :name, prompt: "---")
            %i.fas.fa-chevron-down
        .sell__about__right__wrap
          = f.label :area_id, "発送元の地域"
          %span.required
          .sell__about__right__wrap-box
            = f.collection_select(:area_id, Area.all, :id, :name, prompt: "---")
            %i.fas.fa-chevron-down

        .sell__about__right__wrap
          = f.label :scheduled_sending_date, "発送までの日数"
          %span.required
          .sell__about__right__wrap-box
            = f.select :scheduled_sending_date,[["1~2日で発送", 0], ["2~3日で発送", 1], ["4~7日で発送", 2]], prompt: "---", class: "select"
            %i.fas.fa-chevron-down

    .sell__about.clearfix
      .sell__about__left 販売価格(300〜9,999,999)
      .sell__about__right
        .sell__about__right__wrap
          .sell__about__right__wrap__price
            .sell__about__right__wrap__price-label
              = f.label :price, "価格"
              %span.required
            .sell__about__right__wrap__price-input
              ¥
              .sell__about__right__wrap__price-input-form
                = f.number_field :price, placeholder: "例）300", class: "form"

        .sell__about__right__wrap__fee.clearfix
          .sell__about__right__wrap__fee-left
            販売手数料 (10%)
          .sell__about__right__wrap__fee-right
            ¥
        .sell__about__right__wrap__profit
          .sell__about__right__wrap__profit-left
            販売利益
          .sell__about__right__wrap__profit-right
            ¥
    .sell__about.clearfix
      .sell__about__bottom
          
        = f.submit "出品する", class: 'sell__about__bottom-btn submit'
        %button{type: "button", onclick: "history.back()", class: 'sell__about__bottom-btn back'} もどる


      .sell__about__bottom-text
        %p
          = link_to '#' do
            禁止されている出品
          、
          = link_to '#' do
            行為
          を必ずご確認ください。
        %p
          またブランド品でシリアルナンバー等がある場合はご記載ください。
          = link_to '#' do
            偽ブランド
          の販売は犯罪であり処罰される可能性があります。
        %p
          また、出品をもちまして
          = link_to '#' do
            加盟店規約
          に同意したことになります。


.single-fotter
  %ul.clearfix
    %li.footer-list
      =link_to "#",class:"a" do
        プライバシーポリシー
    %li.footer-list
      =link_to "#" ,class:"a" do
        フリマ利用規約
    %li.footer-list
      =link_to "#", class: "a" do
        特定商取引に関する表記
  .fotter-pict
    = image_tag 'http://furima.tokyo/assets/logo-d3d78326971d78b06e3d6f0ba666d025a8ad681286b4d9e00e7dbe8673bcfd23.svg', height: '60', width: '80'
  .footer-logo
    © FURIMA
 

app/views/products/new.html.haml
.wrapper
  .mypage-content
    = render "shared/loginheader"
    .mypage-main
      .mypage-side-bar
        %nav.mypage-side-bar__nav
          %ul.mypage-side-bar__list
            %li
              = link_to user_adresses_path, class: 'mypage-side-bar__list-item' do
                マイページ
                = icon 'fas', 'chevron-right'
            %li
              = link_to '#', class: 'mypage-side-bar__list-item' do
                お知らせ
                = icon 'fas', 'chevron-right'
            %li
              = link_to '#', class: 'mypage-side-bar__list-item' do
                やることリスト
                = icon 'fas', 'chevron-right'
            %li
              = link_to '#', class: 'mypage-side-bar__list-item' do
                いいね！一覧
                = icon 'fas', 'chevron-right'
            %li
              = link_to '#', class: 'mypage-side-bar__list-item' do
                出品する
                = icon 'fas', 'chevron-right'
            %li
              = link_to '#', class: 'mypage-side-bar__list-item' do
                出品した商品 - 出品中
                = icon 'fas', 'chevron-right'
            %li
              = link_to '#', class: 'mypage-side-bar__list-item' do
                出品した商品 - 取引中
                = icon 'fas', 'chevron-right'
            %li
              = link_to '#', class: 'mypage-side-bar__list-item' do
                出品した商品 - 売却済み
                = icon 'fas', 'chevron-right'
            %li
              = link_to '#', class: 'mypage-side-bar__list-item' do
                購入した商品 - 取引中
                = icon 'fas', 'chevron-right'
            %li
              = link_to '#', class: 'mypage-side-bar__list-item' do
                購入した商品 - 過去の取引
                = icon 'fas', 'chevron-right'
            %li
              = link_to '#', class: 'mypage-side-bar__list-item' do
                ニュース一覧
                = icon 'fas', 'chevron-right'
            %li
              = link_to '#', class: 'mypage-side-bar__list-item' do
                評価一覧
                = icon 'fas', 'chevron-right'
            %li
              = link_to '#', class: 'mypage-side-bar__list-item' do
                ガイド
                = icon 'fas', 'chevron-right'
            %li
              = link_to '#', class: 'mypage-side-bar__list-item' do
                お問い合わせ
                = icon 'fas', 'chevron-right'

          %h1.mypage-side-bar__nav-head
          メルペイ
          %ul.mypage-side-bar__list
            %li
              = link_to '#', class: 'mypage-side-bar__list-item' do
                売上・振り込み申請
                = icon 'fas', 'chevron-right'
            %li
              = link_to '#', class: 'mypage-side-bar__list-item' do
                ポイント
                = icon 'fas', 'chevron-right'
          %h1.mypage-side-bar__nav-head
            設定
          %ul.mypage-side-bar__list
            %li
              = link_to '#', class: 'mypage-side-bar__list-item' do
                プロフィール
                = icon 'fas', 'chevron-right'
            %li
              = link_to '#', class: 'mypage-side-bar__list-item' do
                発送元・お届け先住所変更
                = icon 'fas', 'chevron-right'
            %li
              = link_to credit_cards_index_path , class: 'mypage-side-bar__list-item' do
                支払い方法
                = icon 'fas', 'chevron-right'
            %li
              = link_to '#', class: 'mypage-side-bar__list-item' do
                メール/パスワード
                = icon 'fas', 'chevron-right'
            %li
              = link_to '#', class: 'mypage-side-bar__list-item' do
                本人情報
                = icon 'fas', 'chevron-right'
            %li
              = link_to '#', class: 'mypage-side-bar__list-item' do
                電話番号の確認
                = icon 'fas', 'chevron-right'
            %li
              = link_to '/products/new', class: 'mypage-side-bar__list-item' do
                ログアウト
                = icon 'fas', 'chevron-right'
      = render "shared/logout"
  = render "shared/loginfooter"

app/views/products/show.html.haml
=render 'shared/topheader'
.product-details-main
  .product-details-main__top
    .product-details-main__top-name
      = @product.name
    -if user_signed_in? 
      -if current_user.id == @product.seller_id
        .product-details-main__top-edit
          -if @product.buyer_id.present?
          -else
            .edit
              = link_to edit_product_path(@product),class: "edit-btn" do
                編集
            .destory
              = link_to product_path(@product.id),method: :delete,class: "destory-btn" do
                削除
      -else
    -else
    %br
    .product-details-main__top-image
      %ul
        %li.main-image
          = image_tag @product.images[0].image_url.url,height: '100%', width: '100%'
        %ul.main-sub-list
          - if @product.images[3].present?
            %li.main-image1-sub
              = image_tag @product.images[1].image_url.url,height: '100%', width: '100%'
            %li.main-image2-sub
              = image_tag @product.images[2].image_url.url,height: '100%', width: '100%'
            %li.main-image3-sub
              = image_tag @product.images[3].image_url.url,height: '100%', width: '100%'
          - elsif @product.images[2].present?
            %li.main-image1-sub
              = image_tag @product.images[1].image_url.url,height: '100%', width: '100%'
            %li.main-image2-sub
              = image_tag @product.images[2].image_url.url,height: '100%', width: '100%'
          - elsif @product.images[1].present?
            %li.main-image1-sub
              = image_tag @product.images[1].image_url.url,height: '100%', width: '100%'
          - else
    .item-box-price
      %span
        ¥
        = @product.price
    .item-box-price-details
      %span
        -if @product.postage_burden == '0'
          (税込）送料込み
        -else
          （税込）着払い
    .itemdetails
      = @product.description
    .table
      %table
        %tr
          %th.name 出品者
          %td 
            = @user.nickname
        %tr
          %th.category カテゴリー
          %td.category-list
            .category-btn
              = @category.root.name
            %br
            .category-btn
              >
              = @category.parent.name
            %br
            .category-btn
              >
              = @category.name
        %tr
          %th.brand ブランド 
          %td 
            - if @product.brand_id.present?
              = @brand.name
            - else
        %tr
          %th.brand サイズ
          %td 
            - if @product.size.present?
              = @product.size
            - else
        %tr
          %th.condition 商品状態
          %td 
            = @condition.name
        %tr
          %th.condition 配送方法
          %td 
            = @sending_method.name
        %tr
          %th.condition 配送料の負担
          %td 
            -if @product.postage_burden == '0'
              送料込み(出品者負担)
            -else
              着払い(購入者負担)
        %tr
          %th.condition 発送元の地域
          %td 
            = @area.name
        %tr
          %th.condition 発送日の目安
          %td 
            -if @product.scheduled_sending_date == '0'
              1~2日で発送
            -elsif @product.scheduled_sending_date == '1'
              2~3日で発送
            -else
              4~7日で発送
    .product-details-comment-while 
    .product-details-comments 
      .product-details-comments-textarea 
        = form_for "#" do |f|
          .field-input
            = f.text_area :text,rows:8,cols:86  ,class:"textarea"
          .product-details-comments-note
            相手のことを考え丁寧なコメントを心がけましょう。
            %br
            不快な言葉遣いなどは利用制限や退会処分となることがあります。
          .actions
            = icon('fas','comment', class: 'comment-icon')
            = f.submit "コメントする", class: 'submit-btn'
 
.footer
  %ul.contents
    %li.content
      .content__head
        FURIMAについて
      %ul
        %li
          =link_to url="#" ,class:"ebtn"do
            会社概要（運営会社）
        %li
          =link_to url="#" ,class:"ebtn"do
            プライバシーポリシー
        %li
          =link_to url="#" ,class:"ebtn"do
            FURIMA利用規約
        %li
          =link_to url="#" ,class:"ebtn"do
            ポイントに関する特約
    %li.content
      .content__head
        FURIMAを見る
      %ul
        %li
          =link_to url="#" ,class:"fbtn"do
            カテゴリーー覧
        %li
          =link_to url="#" ,class:"gbtn"do
            ブランドーー覧
    %li.content
      .content__head
        ヘルプ＆ガイド
      %ul
        %li
          =link_to url="#" ,class:"hbtn"do
            FURIMAガイド
        %li
          =link_to url="#" ,class:"ibtn"do
            FURIMAロゴ利用ガイドライン
        %li
          =link_to url="#" ,class:"jbtn"do
            お知らせ
  .footer__logo
    =link_to url="products" ,class:"jbtn"do
      = image_tag 'furima2.svg',  height: '120', width: '150', class: 'iamge11'
    %p
      ©️FURIMA
-if @product.buyer_id.present?
  = link_to root_path ,class:"sell-products" do
    %span.selld-product
      トップへ
      %br
      戻る
    = image_tag 'icon_camera.png',  height: '70px', width: '70px', class: 'iamge11'
-else
  -if user_signed_in? 
    -if UserAdress.where(user_id: current_user.id).present?
      -if current_user.id == @product.seller_id
      -else
        = link_to product_purchase_index_path(params[:id]),class:"sell-product" do
          %span.selld-product
            購入する
          = image_tag 'icon_camera.png',  height: '70px', width: '70px', class: 'iamge11'
    -else
      = link_to new_user_adress_path ,class:"sell-product" do
        %span.selld-product
          住所登録
        = image_tag 'icon_camera.png',  height: '70px', width: '70px', class: 'iamge11'
  -else
    =link_to new_user_session_path,class:"sell" do
      %span.selld
        ログイン
      = image_tag 'icon_camera.png',  height: '70px', width: '70px', class: 'iamge11'
  

  
  